#include "engine.h"
#include <QDebug>
Engine::Engine(QObject *parent) :
    QObject(parent)
{
    qDebug() << "Engine Started";
}

void Engine::processCommand(QString)
{
    // Find out what command was sent, and develope a response.



    emit responseReady("This response was generated by the engine.");
}

